version: "3.9"

services:
  road-defect-app:
    build: .
    image: road-defect-anonymization
    volumes:
      - ./train:/app/train
      - ./outputs:/app/outputs
      - ./app/sensitive_data_masking:/app/app/sensitive_data_masking
      - ./app/watermark_removal:/app/app/watermark_removal
      - ./app/exif_geo_tag:/app/app/exif_geo_tag
    working_dir: /app
    entrypoint: ["python"]
    command: ["app/sensitive_data_masking/mask_plates.py", "--help"]
    tty: true
