services:
  road-defect-app:
    build: .
    image: road-defect-anonymization
    volumes:
      - ./train:/app/train
      - ./outputs:/app/outputs
      - ./app:/app/app
    working_dir: /app
    entrypoint: ["python"]
    command: ["main.py", "--help"]
    tty: true
